= xref:index.adoc[Barbarian]
:copyright: Copyright 2021 René Ferdinand Rivera Morell
:version-label!:
:reproducible:
:nofooter:
:sectlinks:
:linkcss:
:stylesheet: barbarian.css
:icons: font
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠
:source-highlighter: rouge
:rouge-style: bw

== Creating Packages

=== How It Works

Creating and publishing Conan packages for the Barbarian system is based on
using a git repo as the storage for the exported recipe revisions of the
package. That storage happens in a special, fully isolated, branch of the
git repo (`barbarian`). The Barbarian Conan server then uses the recipe
reference to find the repo and serve the recipe to users.

The key to making the arrangement of storing the exported recipes in a
public git repo is in mapping the package reference to the git repo. For
GitHub a reference of `<package>/<version>@<user>/<channel>[#<revision>]`
is mapped as:

`<package>/<version>`:: Mapped to a directory in the `barbarian` branch
containing metadata and exported recipe revisions.
`<user>`:: Mapped to the user or organization in GitHub.
`<channel>`:: Mapped to the git repo containing the recipe(s).

For example `olc-pge/2.15@bfgroup/conan` is mapped to the repo at
`https://github.com/bfgroup/conan/` and the `olc-pge/2.15` directory in
the `barbarian` branch:
`https://github.com/bfgroup/conan/tree/barbarian/olc-pge/2.15`.

IMPORTANT: This means that the `<user>/channel>` part of the reference
is required, unlike packages in Conan Center.

=== Requirements

To manage the aspects of creating and publishing Barbarian style Conan
packages we use the `barbarian` tool. It behaves in a similar way to the
`conan` tool. So it should be fairly obvious how to use it if you already know
the `conan` tool. First step is to install the `barbarian` tool:

[source,shell]
----
$ pip install barbarian
----

=== Package Styles

Creating packages for libraries is possible in a few different ways depending
on what your goals are. There are two basic aims in packaging libraries:
creating a package for your own library, or creating a package for an external
library. For either you have the option to create the package recipe
either externally, i.e. in a git repository outside of the library itself, or
internally, i.e. embedding the recipe with the library source git repo.

==== Standalone: Internal

Standalone embedded package recipes are the easiest to manage if you only want
to package your own library (or contribute directly to someone elses). For this
the recipe information is stored directly in the git repo of the library.

`conanfile.py`::
	The Conan package recipe.
`conandata.yml`::
	_Optional_ specification for the library version sources.

You can place the files anywhere you like in your git repo. The only
requirement is that the optional `conandata.yml` is placed in the same
directory as the `conanfile.py`. A common location being the root of the repo.

==== Standalone: External

An external standalone package recipe makes it possible to separate the package
recipe from the library in its own git repo. Like the standalone internal use
case you can place the recipe files anywhere. But for this the git repo
would only contain the package recipe files and not the library itself.

==== Collection

You can create a collection of many package recipes in a single dedicated
git repository. The arrangement for a collection follows the structure of the
link:https://github.com/conan-io/conan-center-index[Conan Center Index]. For
a `test` library package we would have:

`recipes`::
	Contains a directory for each library package.
`recipes/test`::
	The versions of package recipes for the `test` library.
`recipes/test/config.yml`::
	Configuration listing all the packaged revisions of `test` and the
	subdirectory of the package recipe.
`recipes/test/all`::
	The common case of one generic recipe to handle all revisions would have
	an `all` subdirectory. You can create as many specific version
	subdirectories as needed.
`recipes/test/all/conanfile.py`::
	The Conan package recipe.
`recipes/test/all/conandata.yml`::
	The specification of the library source(s) and optional archive
	verification hashes.

The Conan Center Index provides
link:https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md#more-information-about-recipes[additional information]
on the structure of a collection and the contents of the YAML (`*.yml`) files.

=== The Recipe

Barbarian Conan package recipes follow the same structure of regular packages.
But unlike Conan Center Index recipes, there are no restrictions to what you
can do in them. With the one caveat that there are no binary packages cached.
To make things easy there is a `barbarian new` tool to help you create simple
package recipes to get you started.

[source,shell]
----
$ cd /project/root
$ barbarian new test/0.1.0@user/repo --recipe
----

That will create a template recipe following the <<Standalone: Internal>>
structure. Hence you'll get `conanfile.py` and `conandata.yml` files with
some of the information of your project already filled in, and other
information with angle markers (`<\<<FIELD>>>`) for you to fill in. The tool
does fill in some fields with best guesses. For example setting the
`homepage` to the GitHub `user/repo` location as given in the recipe reference.
Fields you will want to fill in:

`TOPICS`:: Fill in with a list of topics/tags for the library.
`LICENSE`:: The license for the library.
`SHORT_DESCRIPTION`:: A brief, one or two sentence, description of the library.
`LONG_DESCRIPTION`:: A detailed description of the library. Currently only
link:https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc] formatting is
supported for this field.

After this you can use the regular `conan`
link:https://docs.conan.io/en/latest/creating_packages/getting_started.html#creating-and-testing-packages[command]
to build and test that the recipe works. Until we get to exporting the
recipe.

=== Export

In order for one to publish a Barbarian style package it's required to export
the recipe package. In order to not pollute the global Conan recipe cache
we use a special `barbarian export` command that places the package locally
in a `<git-repo-root>/.conan` directory. Continuing with the previous
`test` recipe:

[source,shell]
----
$ cd location/of/conanfile
$ barbarian export . test/0.1.0@user/repo
----

TIP: The `barbarian new` command will also add `/.conan/` to your
`.gitignore` file. Hence if you didn't use `conan new` It's recommended to add
`/.conan/` manually to your `.gitignore` root file to avoid accidentally adding
this internal directory to git.

=== Upload

Now that we have the recipe exported we can publish it for others to use. For
that we can use the `barbarian upload` command. Which, on the surface, has an
equivalent effect than the `conan upload` command. Except that instead of
uploading to the specialized Artifactory repository, it copies the package to
the special `barbarian` branch with extra meta data for the Barbarian Conan
server to find.

[source,shell]
----
$ barbarian upload test/0.1@user/repo
----

Not only does that put the recipe in the `barbarian` branch. It will also push
that branch upstream to GitHub.

WARNING: Note that for this arrangement to work the git repository containing
the recipe and package must be publicly accessible.

=== Continuous Integration

At this point you have a working and published package. But it's good to test
the recipe. For that you can add some CI testing to check that it's all in
working order. The `barbarian new` tool can also help with that. By using the
`--ci` option you can add a default CI setup:

[source,shell]
----
$ barbarian new test/0.1.0@user/repo --ci 
----

That creates a GitHub Actions `barbarian.yml` workflow file that uses the
link:https://github.com/bincrafters/bincrafters-package-tools[Bincrafters Package Tools]
to automatically generate and run various checks depending on the style
of recipe you have.

include::footer.part.adoc[]
