name: 'Rosina: Tracklog'

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - { uses: 'actions/setup-python@v2.2.2', with: { python-version: '3.x' } }
