name: "Rosina: Tracklog"

on:
  push:
    branches: []
  pull_request:
    branches: []
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2.2.2"
        with: { python-version: "3.x" }
      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Rosina
        run: |
          cd src/rosina
          pip install .
      - name: Process Tracklog
        run: |
          rosina --help
