name: "Tracklog"

on:
  schedule:
    - cron: "0/20 * * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tracklog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2.2.2"
        with: { python-version: "3.x" }
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
      - name: Setup Server Tools
        run: |
          pip install .
      - name: Process Tracklog
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
        run: barbarian_rosina tracklog
